// Map by stable key (slug/id/name). Each preset may define its own `order`.
export const BUILDING_PRESETS = {
  'Standard Carport': {
    order: [
      'enabledAllBuilding',
      'Carportsbuilding',
      'barn_Width',
      'barn_Length',
      'barn_height',
      'trimColor',
      'roofColor',
      'fontwalls',
      'backwalls',
      'leftwalls',
      'rightwalls',
      'barn_heightS',
      'rightleansFalse',
      'leftleansFalse',
      'backstorage',
      'leftstorage',
    ],
    enabledAllBuilding: null,
    barn_heightS: null,
    Carportsbuilding: null,
    barn_height: 10,
    barn_Width: 24,
    barn_Length: 40,
    trimColor: '#832c00',
    roofColor: '#832c00',
    backstorage: 'disabled',
    leftstorage: 'disabled',
    fontwalls: 'Open',
    backwalls: 'Open',
    leftwalls: 'Open',
    rightwalls: 'Open',
    rightleansFalse: null,
    leftleansFalse: null,
    garageroll: null,
  },
  'Triple Wide Carpot': {
    order: [
      'enabledAllBuilding',
      'TripleCarportsbuilding',
      'garageroll',
      'barn_height',
      'barn_Width',
      'barn_Length',
      'TripleCarportsbuilding',
      'fontwalls',
      'backwalls',
      'leftwalls',
      'rightwalls',
      'trimColor',
      'roofColor',
      'backstorage',
      'rightleansFalse',
      'leftleansFalse',
      'leftstorage',
      'barn_heightS',
    ],
    enabledAllBuilding: null,
    barn_heightS: null,
    TripleCarportsbuilding: null,
    barn_height: 12,
    barn_Width: 30,
    barn_Length: 40,
    trimColor: '#124934',
    roofColor: '#124934',
    backstorage: 'disabled',
    leftstorage: 'disabled',
    fontwalls: 'Open',
    backwalls: 'Open',
    leftwalls: 'Open',
    rightwalls: 'Open',
    rightleansFalse: null,
    leftleansFalse: null,
  },
  'Utility Carpot': {
    order: [
      'enabledAllBuilding',
      'UtilityCarportsbuilding',
      'barn_height',
      'barn_Width',
      'barn_Length',
      'trimColor',
      'roofColor',
      'wallColor',
      'backstorage',
      'leftstorage',
      'fontwalls',
      'backwalls',
      'leftwalls',
      'rightwalls',
      'storageFeet',
      'centerstorage',
      'Center',
      'garageroll',
      'rightleansFalse',
      'leftleansFalse',
      'barn_heightD',
    ],
    enabledAllBuilding: null,
    UtilityCarportsbuilding: null,
    barn_height: 10,
    barn_Width: 24,
    barn_Length: 40,
    trimColor: '#d4dcdc',
    roofColor: '#d4dcdc',
    wallColor: '#9c3b20',
    backstorage: 'enabled',
    leftstorage: 'disabled',
    fontwalls: 'Open',
    backwalls: 'Open',
    leftwalls: 'Open',
    rightwalls: 'Open',
    storageFeet: 15,
    centerstorage: 'Front',
    Center: 'Select',
    garageroll: null,
    rightleansFalse: null,
    leftleansFalse: null,
    barn_heightD: null,
  },
  'Standard Garage': {
    order: [
      'enabledAllBuilding',
      'WainscotFalse',
      'garag1',
      'barn_height',
      'barn_Width',
      'barn_Length',
      'leftstorage',
      'wallColor',
      'trimColor',
      'roofColor',
      'fontwalls',
      'backwalls',
      'leftwalls',
      'rightwalls',
      'WainscotTrue',
      'WainscotColor',
      'backstorage',
      'rightleansFalse',
      'leftleansFalse',
      'barn_heightS',
    ],
    enabledAllBuilding: null,
    WainscotFalse: null,
    garag1: null,
    barn_height: 10,
    barn_Width: 24,
    barn_Length: 40,
    leftstorage: 'disabled',
    wallColor: '#818c8f',
    trimColor: '#124934',
    roofColor: '#124934',
    fontwalls: 'Closed',
    backwalls: 'Closed',
    leftwalls: 'Closed',
    rightwalls: 'Closed',
    WainscotTrue: null,
    WainscotColor: '#124934',
    backstorage: 'disabled',
    rightleansFalse: null,
    leftleansFalse: null,
    barn_heightS: null,
  },
  'Triple Wide Garage': 
  {
    order: [
      'enabledAllBuilding',
      'WainscotFalse',
      'garag2',
      'barn_height',
      'barn_Width',
      'barn_Length',
      'leftstorage',
      'fontwalls',
      'backwalls',
      'leftwalls',
      'rightwalls',
      'wallColor',
      'trimColor',
      'roofColor',
      'WainscotTrue',
      'WainscotColor',
      'backstorage',
      'rightleansFalse',
      'leftleansFalse',
      'barn_heightS'
    ],
    enabledAllBuilding: null,
    WainscotFalse: null,
    garag2: null,
    barn_height: 10,
    barn_Width: 24,
    barn_Length: 40,
    leftstorage: 'disabled',
    fontwalls: 'Closed',
    backwalls: 'Closed',
    leftwalls: 'Closed',
    rightwalls: 'Closed',
    wallColor: '#818c8f',
    trimColor: '#551921',
    roofColor: '#551921',
    WainscotTrue: null,
    WainscotColor: '#551921',
    backstorage: 'disabled',
    rightleansFalse: null,
    leftleansFalse: null,
    barn_heightS: null,
  },
  'Garage with Lean TO':  {
    order: [
      'enabledAllBuilding',
      'WainscotFalse',
      'garag3',
      'barn_height',
      'barn_Width',
      'barn_Length',
      'leftstorage',
      'fontwalls',
      'backwalls',
      'leftwalls',
      'rightwalls',
      'roofColor',
      'wallColor',
      'trimColor',
      'barn_heightS',
      'rightleansTrue',
      'leansheightR',
      'leansRightW',
      'leansRightL',
      'WainscotTrue',
      'WainscotColor',
      'backstorage',
      'leftleansFalse',
      'Rfontwalls',
      'Rsidewalls',
      'Rbackwalls'
    ],
    enabledAllBuilding: null,
    WainscotFalse: null,
    garag3: null,
    barn_height: 12,
    barn_Width: 24,
    barn_Length: 40,
    leftstorage: 'disabled',
    fontwalls: 'Closed',
    backwalls: 'Closed',
    leftwalls: 'Closed',
    rightwalls: 'Closed',
    roofColor: '#b1917f',
    wallColor: '#832c00',
    trimColor: '#832c00',
    barn_heightS: null,
    rightleansTrue: null,
    leansheightR: 7,
    leansRightW: 12,
    leansRightL : 40,
    WainscotTrue: null,
    WainscotColor: '#b1917f',
    backstorage: 'disabled',
    leftleansFalse: null,
    Rfontwalls: 'Open',
    Rsidewalls: 'Open',
    Rbackwalls: 'Open',
  },
  'Standard Garage': {
    order: [
      'barn2',
      'barn_height',
      'barn_Width',
      'barn_Length',
      'fontwalls',
      'backwalls',
      'leftwalls',
      'rightwalls',
      'trimColor',
      'roofColor',
      'wallColor',
      'backstorage',
      'rightleansTrue',
      'leftleansTrue',
      'WainscotFalse',
      'leansRightW',
      'leansLeftW',
      'Rfontwalls',
      'Rbackwalls',
      'Rsidewalls',
      'Lfontwalls',
      'Lbackwalls',
      'Lsidewalls',
      'leansheightL',
      'leansheightR',
      'leansRightL',
      'leansLeftL'
    ],
    barn2: null,
    barn_Width: 24,
    barn_Length: 40,
    barn_height: 12,
    fontwalls: 'Closed',
    backwalls: 'Closed',
    leftwalls: 'Closed',
    rightwalls: 'Closed',
    trimColor: '#d4dcdc',
    roofColor: '#d4dcdc',
    wallColor: '#628aa0',
    backstorage: 'disabled',
    rightleansTrue: null,
    leftleansTrue: null,
    WainscotFalse: null,
    leansRightW: 12,
    leansLeftW: 12,
    Rfontwalls: 'Closed',
    Rbackwalls: 'Closed',
    Rsidewalls: 'Closed',
    Lfontwalls: 'Open',
    Lbackwalls: 'Closed',
    Lsidewalls: 'Closed',
    leansheightL: 8,
    leansheightR: 8,
    leansRightL : 40,
    leansLeftL : 40
  },
  'Raised Center Barns': {
    order: [
      'barn1',
      'barn_height',
      'barn_Width',
      'barn_Length',
      'fontwalls',
      'backwalls',
      'leftwalls',
      'rightwalls',
      'roofColor',
      'trimColor',
      'wallColor',
      'rightleansTrue',
      'leftleansTrue',
      'Rsidewalls',
      'Rbackwalls',
      'Rfontwalls',
      'Lsidewalls',
      'Lfontwalls',
      'Lbackwalls',
      'barn_Width',  // For the second occurrence with width variable
      'barn_Length', // For the second occurrence with depth variable
      'leansheightR',
      'leansRightW',
      'leansheightL',
      'leansLeftW',
      'backstorage',
      'leansRightL',
      'leansLeftL'
    ],
    barn1: null,
    barn_Width: 24,
    barn_Length: 40,
    barn_height: 12,
    fontwalls: 'Closed',
    backwalls: 'Closed',
    leftwalls: 'Closed',
    rightwalls: 'Closed',
    roofColor: '#818c8f',
    trimColor: '#818c8f',
    wallColor: '#9c3b20',
    rightleansTrue: null,
    leftleansTrue: null,
    Rsidewalls: 'Closed',
    Rbackwalls: 'Closed',
    Rfontwalls: 'Closed',
    Lsidewalls: 'Closed',
    Lfontwalls: 'Closed',
    Lbackwalls: 'Closed',
    leansheightR: 7,
    leansRightW: 12,
    leansheightL: 7,
    leansLeftW: 12,
    backstorage: 'disabled',
    leansRightL : 40,
    leansLeftL : 40
  },
  'RV Covers': {
    order: [
      'enabledAllBuilding',
      'rv1',
      'barn_height',
      'barn_Width',
      'barn_Length',
      'fontwalls',
      'backwalls',
      'leftwalls',
      'rightwalls',
      'trimColor',
      'roofColor',
      'backstorage',
      'rightleansFalse',
      'leftleansFalse',
      'leftstorage',
      'barn_heightS'
    ],
    enabledAllBuilding: null,
    rv1: null,
    barn_height: 15,
    barn_Width: 20,
    barn_Length: 30,
    fontwalls: 'Open',
    backwalls: 'Open',
    leftwalls: 'Open',
    rightwalls: 'Open',
    trimColor: '#832c00',
    roofColor: '#832c00',
    backstorage: 'disabled',
    rightleansFalse: null,
    leftleansFalse: null,
    leftstorage: 'disabled',
    barn_heightS: null
  },
  'Commercials Carpot': {
    order: [
      'enabledAllBuilding',
      'Commercial1',
      'barn_Width',
      'barn_Length',
      'barn_height',
      'fontwalls',
      'backwalls',
      'leftwalls',
      'rightwalls',
      'trimColor',
      'roofColor',
      'wallColor',
      'backstorage',
      'rightleansFalse',
      'leftleansFalse',
      'leftstorage',
      'barn_heightS',
      'barn_heightT'
    ],
    enabledAllBuilding: null,
    Commercial1: null,
    Standardbarn1: null,
    Standardbarn2: null,
    barn_Width: 50,
    barn_Length: 40,
    barn_height: 20,
    fontwalls: 'Open',
    backwalls: 'Open',
    leftwalls: 'Closed',
    rightwalls: 'Closed',
    trimColor: '#d4dcdc',
    roofColor: '#d4dcdc',
    wallColor: '#9c3b20',
    backstorage: 'disabled',
    rightleansFalse: null,
    leftleansFalse: null,
    leftstorage: 'disabled',
    barn_heightS: null,
    barn_heightT: null
  },
  'Commercial Building': {
    order: [
      'enabledAllBuilding',
      'Commercial1',
      'barn_Width',
      'barn_Length',
      'barn_height',
      'fontwalls',
      'backwalls',
      'leftwalls',
      'rightwalls',
      'trimColor',
      'roofColor',
      'wallColor',
      'backstorage',
      'rightleansFalse',
      'leftleansFalse',
      'leftstorage',
      'barn_heightS',
      'barn_heightT'
    ],
    enabledAllBuilding: null,
    Commercial1: null,
    Standardbarn1: null,
    Standardbarn2: null,
    barn_Width: 50,
    barn_Length: 40,
    barn_height: 20,
    fontwalls: 'Open',
    backwalls: 'Open',
    leftwalls: 'Open',
    rightwalls: 'Open',
    trimColor: '#d4dcdc',
    roofColor: '#d4dcdc',
    wallColor: '#9c3b20',
    backstorage: 'disabled',
    rightleansFalse: null,
    leftleansFalse: null,
    leftstorage: 'disabled',
    barn_heightS: null,
    barn_heightT: null
  },
  'FREE STANDING BUILDINGS': {
    order: [
      'enabledAllBuilding',
      'free1',
      'barn_Width',
      'barn_Length',
      'barn_height',
      'fontwalls',
      'backwalls',
      'leftwalls',
      'rightwalls',
      'trimColor',
      'roofColor',
      'wallColor',
      'rightleansFalse',
      'leftleansFalse',
      'HeightL',
      'HeightR'
    ],
    enabledAllBuilding: null,
    free1: null,
    barn_Width: 14,
    barn_Length: 40,
    barn_height: null,
    fontwalls: 'Closed',
    backwalls: 'Closed',
    leftwalls: 'Closed',
    rightwalls: 'Closed',
    trimColor: '#d4dcdc',
    roofColor: '#832c00',
    wallColor: '#832c00',
    rightleansFalse: null,
    leftleansFalse: null,
    HeightL: 8,
    HeightR: 11,
    leftstorage: 'disabled',
    backstorage: 'disabled'
  },
  'FREE STANDING LEAN-TOS': {
    order: [
      'enabledAllBuilding',
      'free2',
      'barn_Width',
      'barn_Length',
      'barn_height',
      'fontwalls',
      'backwalls',
      'leftwalls',
      'rightwalls',
      'trimColor',
      'roofColor',
      'wallColor',
      'rightleansFalse',
      'leftleansFalse',
      'HeightL',
      'HeightR'
    ],
    enabledAllBuilding: null,
    free2: null,
    barn_Width: 14,
    barn_Length: 40,
    barn_height: null,
    fontwalls: 'Open',
    backwalls: 'Open',
    leftwalls: 'Open',
    rightwalls: 'Open',
    trimColor: '#d4dcdc',
    roofColor: '#832c00',
    wallColor: '#832c00',
    rightleansFalse: true,
    leftleansFalse: true,
    HeightL: 8,
    HeightR: 11,
    leftstorage: 'disabled',
    backstorage: 'disabled'
  }
};