// Map by stable key (slug/id/name). Each preset may define its own `order`.
export const BUILDING_PRESETS = {
  'Standard Carport': {
    order: [
      'enabledAllBuilding',
      'Carportsbuilding',
      'barn_Width',
      'barn_Length',
      'barn_height',
      'trimColor',
      'roofColor',
      'fontwalls',
      'backwalls',
      'leftwalls',
      'rightwalls',
      'barn_heightS',
      'rightleansFalse',
      'leftleansFalse',
      'backstorage',
      'leftstorage',
    ],
    enabledAllBuilding: null,
    barn_heightS: null,
    Carportsbuilding: null,
    barn_height: 10,
    barn_Width: 24,
    barn_Length: 40,
    trimColor: '#832c00',
    roofColor: '#832c00',
    backstorage: 'disabled',
    leftstorage: 'disabled',
    fontwalls: 'Open',
    backwalls: 'Open',
    leftwalls: 'Open',
    rightwalls: 'Open',
    rightleansFalse: null,
    leftleansFalse: null,
    garageroll: null,
  },
  'Triple Wide Carpot': {
    order: [
      'enabledAllBuilding',
      'TripleCarportsbuilding',
      'garageroll',
      'barn_height',
      'barn_Width',
      'barn_Length',
      'TripleCarportsbuilding',
      'fontwalls',
      'backwalls',
      'leftwalls',
      'rightwalls',
      'trimColor',
      'roofColor',
      'backstorage',
      'rightleansFalse',
      'leftleansFalse',
      'leftstorage',
      'barn_heightS',
    ],
    enabledAllBuilding: null,
    barn_heightS: null,
    TripleCarportsbuilding: null,
    barn_height: 12,
    barn_Width: 30,
    barn_Length: 40,
    trimColor: '#124934',
    roofColor: '#124934',
    backstorage: 'disabled',
    leftstorage: 'disabled',
    fontwalls: 'Open',
    backwalls: 'Open',
    leftwalls: 'Open',
    rightwalls: 'Open',
    rightleansFalse: null,
    leftleansFalse: null,
  },
  'Utility Carpot': {
    order: [
      'enabledAllBuilding',
      'UtilityCarportsbuilding',
      'barn_height',
      'barn_Width',
      'barn_Length',
      'trimColor',
      'roofColor',
      'wallColor',
      'backstorage',
      'leftstorage',
      'fontwalls',
      'backwalls',
      'leftwalls',
      'rightwalls',
      'storageFeet',
      'centerstorage',
      'Center',
      'garageroll',
      'rightleansFalse',
      'leftleansFalse',
      'barn_heightD',
    ],
    enabledAllBuilding: null,
    UtilityCarportsbuilding: null,
    barn_height: 10,
    barn_Width: 24,
    barn_Length: 40,
    trimColor: '#d4dcdc',
    roofColor: '#d4dcdc',
    wallColor: '#9c3b20',
    backstorage: 'enabled',
    leftstorage: 'disabled',
    fontwalls: 'Open',
    backwalls: 'Open',
    leftwalls: 'Open',
    rightwalls: 'Open',
    storageFeet: 15,
    centerstorage: 'Front',
    Center: 'Select',
    garageroll: null,
    rightleansFalse: null,
    leftleansFalse: null,
    barn_heightD: null,
  },
  'Standard Garage': {
    order: [
      'enabledAllBuilding',
      'WainscotFalse',
      'garag1',
      'barn_height',
      'barn_Width',
      'barn_Length',
      'leftstorage',
      'wallColor',
      'trimColor',
      'roofColor',
      'fontwalls',
      'backwalls',
      'leftwalls',
      'rightwalls',
      'WainscotTrue',
      'WainscotColor',
      'backstorage',
      'rightleansFalse',
      'leftleansFalse',
      'barn_heightS',
    ],
    enabledAllBuilding: null,
    WainscotFalse: null,
    garag1: null,
    barn_height: 10,
    barn_Width: 24,
    barn_Length: 40,
    leftstorage: 'disabled',
    wallColor: '#818c8f',
    trimColor: '#124934',
    roofColor: '#124934',
    fontwalls: 'Closed',
    backwalls: 'Closed',
    leftwalls: 'Closed',
    rightwalls: 'Closed',
    WainscotTrue: null,
    WainscotColor: '#124934',
    backstorage: 'disabled',
    rightleansFalse: null,
    leftleansFalse: null,
    barn_heightS: null,
  },
  'Triple Wide Garage': 
  {
    order: [
      'enabledAllBuilding',
      'WainscotFalse',
      'garag2',
      'barn_height',
      'barn_Width',
      'barn_Length',
      'leftstorage',
      'fontwalls',
      'backwalls',
      'leftwalls',
      'rightwalls',
      'wallColor',
      'trimColor',
      'roofColor',
      'WainscotTrue',
      'WainscotColor',
      'backstorage',
      'rightleansFalse',
      'leftleansFalse',
      'barn_heightS'
    ],
    enabledAllBuilding: null,
    WainscotFalse: null,
    garag2: null,
    barn_height: 10,
    barn_Width: 24,
    barn_Length: 40,
    leftstorage: 'disabled',
    fontwalls: 'Closed',
    backwalls: 'Closed',
    leftwalls: 'Closed',
    rightwalls: 'Closed',
    wallColor: '#818c8f',
    trimColor: '#551921',
    roofColor: '#551921',
    WainscotTrue: null,
    WainscotColor: '#551921',
    backstorage: 'disabled',
    rightleansFalse: null,
    leftleansFalse: null,
    barn_heightS: null,
  },
  'Garage with Lean TO':  {
    order: [
      'enabledAllBuilding',
      'WainscotFalse',
      'garag3',
      'barn_height',
      'barn_Width',
      'barn_Length',
      'leftstorage',
      'fontwalls',
      'backwalls',
      'leftwalls',
      'rightwalls',
      'roofColor',
      'wallColor',
      'trimColor',
      'barn_heightS',
      'rightleansTrue',
      'leansheightR',
      'leansRightW',
      'leansRightL',
      'WainscotTrue',
      'WainscotColor',
      'backstorage',
      'leftleansFalse',
      'Rfontwalls',
      'Rsidewalls',
      'Rbackwalls'
    ],
    enabledAllBuilding: null,
    WainscotFalse: null,
    garag3: null,
    barn_height: 12,
    barn_Width: 24,
    barn_Length: 40,
    leftstorage: 'disabled',
    fontwalls: 'Closed',
    backwalls: 'Closed',
    leftwalls: 'Closed',
    rightwalls: 'Closed',
    roofColor: '#b1917f',
    wallColor: '#832c00',
    trimColor: '#832c00',
    barn_heightS: null,
    rightleansTrue: null,
    leansheightR: 7,
    leansRightW: 12,
    leansRightL : 40,
    WainscotTrue: null,
    WainscotColor: '#b1917f',
    backstorage: 'disabled',
    leftleansFalse: null,
    Rfontwalls: 'Open',
    Rsidewalls: 'Open',
    Rbackwalls: 'Open',
  },
};